DROP TABLE IF EXISTS student_unit_progress CASCADE;
DROP TABLE IF EXISTS script_blocks CASCADE;
DROP TABLE IF EXISTS unit_quizzes CASCADE;
DROP TABLE IF EXISTS course_units CASCADE;
DROP TABLE IF EXISTS course_enrollments CASCADE;
DROP TABLE IF EXISTS courses CASCADE;
